### ISSUE TITLE
'RedisCache' object has no attribute '_client'

### ISSUE THREAD

**Issue by scream4ik** [ui/django-rq#143]
On my few projects i got same error:
AttributeError: 'RedisCache' object has no attribute '_client'

**Traceback**
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/production/.virtualenvs/flinders/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/production/.virtualenvs/flinders/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/home/production/.virtualenvs/flinders/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/production/.virtualenvs/flinders/local/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/production/.virtualenvs/flinders/local/lib/python2.7/site-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/home/production/.virtualenvs/flinders/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/production/.virtualenvs/flinders/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 74, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/production/flinders/apps/catalog/admin.py", line 9, in <module>
    from .tasks import send_mail
  File "/home/production/flinders/apps/catalog/tasks.py", line 10, in <module>
    @job
  File "/home/production/.virtualenvs/flinders/local/lib/python2.7/site-packages/django_rq/decorators.py", line 30, in job
    queue = get_queue(queue)
  File "/home/production/.virtualenvs/flinders/local/lib/python2.7/site-packages/django_rq/queues.py", line 119, in get_queue
    connection=get_connection(name), async=async,
  File "/home/production/.virtualenvs/flinders/local/lib/python2.7/site-packages/django_rq/queues.py", line 93, in get_connection
    return get_redis_connection(QUEUES[name], use_strict_redis)
  File "/home/production/.virtualenvs/flinders/local/lib/python2.7/site-packages/django_rq/queues.py", line 80, in get_redis_connection
    return cache._client
AttributeError: 'RedisCache' object has no attribute '_client'
```

**Project requirements**
```
click==6.2
Django==1.8.7
django-cleanup==0.4.0
django-debug-toolbar==1.4
django-embed-video==1.0.0
-e git+https://github.com/NextGear/django-media-manager.git@3d3129eb1bbb32c42f6c000cb141813f3a8bca16#egg=django_media_manager-master
django-modeltranslation==0.10.2
django-mptt==0.7.4
django-pure-pagination==0.2.1
django-redis-cache==1.6.5
django-redis-sessions==0.5.0
django-rq==0.8.0
django-suit==0.2.15
django-suit-ckeditor==0.0.2
MySQL-python==1.2.5
Pillow==3.0.0
pygeocoder==1.2.5
pytils==0.3
pytz==2015.7
redis==2.10.5
requests==2.8.1
rq==0.5.6
sorl-thumbnail==12.3
sqlparse==0.1.18
uWSGI==2.0.11.2
wheel==0.26.0
```

When i changed 80 line in function get_redis_connection (file queues.py)
```
return cache._client
```
to
```
return cache.get_master_client()
```
all fine

**Comment by selwin** [comment]
Mind opening a PR with a try/except around the problematic line?

**Comment by scream4ik** [comment]
I agree with you. But it seems that have this problem only me. Maybe I'm doing something wrong or it's really bug

**Comment by JurajKavka** [comment]
I have this problem too in my project. As a workaround, I have downgraded django-redis-cache to older version.

`pip install django-redis-cache==0.13.1`

**Comment by selwin** [comment]
Mind opening a PR for this so we can fix it for everyone? ;)

**Comment by pratyushsharma** [comment]
I am facing the same error.

**Comment by scream4ik** [comment]
We are waiting next release with fix. But now you can fix it yourself in your environment https://github.com/ui/django-rq/commit/07674a13d621b10294a33c3bfb0b9133378199b6
