### ISSUE TITLE
Email job fails with authentication error

### ISSUE THREAD

**Issue by azolson** [ui/django-rq#148]
Hi,

i'm trying to enqueue a send_mail job as follows:
```
django_rq.enqueue(
       send_mail,
       newClaim.linkedOffer.commsPromoHeadline,
       msg_plain,
       settings.DEFAULT_FROM_EMAIL,
       [newRecipient.email],
       html_message=msg_html,
   )
```
this fails with an authentication error (see further down).

The following code block works however (no enqueueing):
```
send_mail(
    newClaim.linkedOffer.commsPromoHeadline,
    msg_plain,
    settings.DEFAULT_FROM_EMAIL,
    [newRecipient.email],
    html_message=msg_html,
)
```

Error produced when django-rq is being used is:
```
Traceback (most recent call last):
  File "/home/user1/webapps/dev_django_platform/ENV/lib/python2.7/site-packages/rq/worker.py", line 568, in perform_job
    rv = job.perform()
  File "/home/user1/webapps/dev_django_platform/ENV/lib/python2.7/site-packages/rq/job.py", line 495, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/home/user1/webapps/dev_django_platform/lib/python2.7/Django-1.7.7-py2.7.egg/django/core/mail/__init__.py", line 62, in send_mail
    return mail.send()
  File "/home/user1/webapps/dev_django_platform/lib/python2.7/Django-1.7.7-py2.7.egg/django/core/mail/message.py", line 286, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/user1/webapps/dev_django_platform/lib/python2.7/Django-1.7.7-py2.7.egg/django/core/mail/backends/smtp.py", line 92, in send_messages
    new_conn_created = self.open()
  File "/home/user1/webapps/dev_django_platform/lib/python2.7/Django-1.7.7-py2.7.egg/django/core/mail/backends/smtp.py", line 59, in open
    self.connection.login(self.username, self.password)
  File "/usr/local/lib/python2.7/smtplib.py", line 622, in login
    raise SMTPAuthenticationError(code, resp)
SMTPAuthenticationError: (535, '5.7.3 Authentication unsuccessful')
```

Any ideas how I can get django-rq working for this? It's been suggested here http://stackoverflow.com/a/34642770/763880 that it's because a worker would not have access to all of the details to make a successful connection such as authentication details that might be contained in Django settings?

**Comment by selwin** [comment]
This is not a but in django-rq so I'm gonna close this issue. Try printing out all the SMTP related settings in your function and see if your worker correctly reads them.

You're running the worker with "python manage.py rqworker", right?
