### ISSUE TITLE
AttributeError: 'RedisCache' object has no attribute '_client'

### ISSUE THREAD

**Issue by m-vdb** [ui/django-rq#161]
Looks like it's not compatible with django-redis-cache==1.6.5:

```
Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File ".snip./venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File ".snip./venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File ".snip./venv/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File ".snip./venv/lib/python2.7/site-packages/django/core/management/base.py", line 398, in execute
    self.check()
  File ".snip./venv/lib/python2.7/site-packages/django/core/management/base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File ".snip./venv/lib/python2.7/site-packages/django/core/checks/registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File ".snip./venv/lib/python2.7/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File ".snip./venv/lib/python2.7/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    for pattern in resolver.url_patterns:
  File ".snip./venv/lib/python2.7/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File ".snip./venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File ".snip./venv/lib/python2.7/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File ".snip./venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File ".snip./project/urls.py", line 19, in <module>
    from project.views import interface, oauth, webhooks
  File ".snip./project/views/webhooks.py", line 10, in <module>
    from project import tasks
  File ".snip./project/tasks.py", line 9, in <module>
    @job
  File ".snip./venv/lib/python2.7/site-packages/django_rq/decorators.py", line 30, in job
    queue = get_queue(queue)
  File ".snip./venv/lib/python2.7/site-packages/django_rq/queues.py", line 119, in get_queue
    connection=get_connection(name), async=async,
  File ".snip./venv/lib/python2.7/site-packages/django_rq/queues.py", line 93, in get_connection
    return get_redis_connection(QUEUES[name], use_strict_redis)
  File ".snip./venv/lib/python2.7/site-packages/django_rq/queues.py", line 80, in get_redis_connection
    return cache._client
AttributeError: 'RedisCache' object has no attribute '_client'
```

And my settings:
```python
RQ_QUEUES = {
    'default': {
        'USE_REDIS_CACHE': 'default',
    }
}
```

**Comment by scream4ik** [comment]
on master branch this issue already fixed. Waiting new version)

**Comment by m-vdb** [comment]
can there be a release on pip?

**Comment by scream4ik** [comment]
https://github.com/ui/django-rq/issues/154
