### ISSUE TITLE
ImportError: No module named None

### ISSUE THREAD

**Issue by eddyLazar** [ui/django-rq#197]
i get this error for each job, sending to queue

`Traceback (most recent call last):
  File "/webapps/hillel_project/local/lib/python2.7/site-packages/rq/worker.py", line 588, in perform_job
    rv = job.perform()
  File "/webapps/hillel_project/local/lib/python2.7/site-packages/rq/job.py", line 498, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/webapps/hillel_project/local/lib/python2.7/site-packages/rq/job.py", line 206, in func
    return import_attribute(self.func_name)
  File "/webapps/hillel_project/local/lib/python2.7/site-packages/rq/utils.py", line 150, in import_attribute
    module = importlib.import_module(module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named None
Traceback (most recent call last):
  File "/webapps/hillel_project/local/lib/python2.7/site-packages/rq/worker.py", line 588, in perform_job
    rv = job.perform()
  File "/webapps/hillel_project/local/lib/python2.7/site-packages/rq/job.py", line 498, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/webapps/hillel_project/local/lib/python2.7/site-packages/rq/job.py", line 206, in func
    return import_attribute(self.func_name)
  File "/webapps/hillel_project/local/lib/python2.7/site-packages/rq/utils.py", line 150, in import_attribute
    module = importlib.import_module(module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)`

**Comment by selwin** [comment]
This doesn't look like a bug in Django-RQ. You need to make sure that the function that you're running can be imported from the worker environment.

**Comment by TravisDart** [comment]
I ran into this issue, and it was because I'd just installed RQ and wanted to "try it out" in the Django shell. Unfortunately, functions must be visible to the RQ worker, and functions defined in the shell are not. To try it out, create a function in a test file or something, then run it.

Thought I'd point that out for anyone else who is running into this same issue.
