### ISSUE TITLE
Jobs Failing

### ISSUE THREAD

**Issue by ssanthosh243** [ui/django-rq#234]
Hi,

I have been using django-rq in the project and suddenly i started receiving this error when submitting the jobs.

`Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/site-packages/rq/worker.py", line 700, in perform_job
    rv = job.perform()
  File "/app/.heroku/python/lib/python2.7/site-packages/rq/job.py", line 500, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    if test_func(request.user):
AttributeError: 'unicode' object has no attribute 'user'`

If it helps, I have this project running in Heroku. I have verified my project code, and also tried submitting jobs manually. Still the jobs keep failing.

**Comment by ssanthosh243** [comment]
I have found the root cause of this issue. It is due to the authentication system in Django preventing the jobs to run.
