### ISSUE TITLE
Use django's autoreload feature

### ISSUE THREAD

**Issue by megapctr** [ui/django-rq#262]
Autoreloading has been a long-requested RQ feature. Since it doesn't seem it's going to be implemented in a while, I thought that at least django-rq could use runserver's auto-reloading feature.

I looked at how runserver does autoreloading and it's much simpler than I thought. Check it out yourself: https://github.com/django/django/blob/master/django/core/management/commands/runserver.py#L98-L105

Of course this may cause issues with workers being stopped mid-job or some problems across various django versions, but we should at least research this a bit more 😃 

I can prepare a PR for this.

**Comment by selwin** [comment]
Yeah, a PR would be welcome.

Whether or not workers are stopped mid job depends on how `autoreload.main` is implemented. If it sends a `SIGKILL` to the management command, we're golden as RQ will wait until the job is finished before shutting down.

**Comment by megapctr** [comment]
I quickly hit a brick wall unfortunately 😞 Looks like we'll need to at least subclass the Worker
```worker_1     | Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fdf3b5c17b8>
worker_1     | Traceback (most recent call last):
worker_1     |   File "/usr/local/lib/python3.6/site-packages/django/utils/autoreload.py", line 228, in wrapper
worker_1     |     fn(*args, **kwargs)
worker_1     |   File "/backend/django-rq/django_rq/management/commands/rqworker.py", line 127, in inner_handle
worker_1     |     w.work(burst=options.get('burst', False))
worker_1     |   File "/usr/local/lib/python3.6/site-packages/rq/worker.py", line 448, in work
worker_1     |     self._install_signal_handlers()
worker_1     |   File "/usr/local/lib/python3.6/site-packages/rq/worker.py", line 363, in _install_signal_handlers
worker_1     |     signal.signal(signal.SIGINT, self.request_stop)
worker_1     |   File "/usr/local/lib/python3.6/signal.py", line 47, in signal
worker_1     |     handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
worker_1     | ValueError: signal only works in main thread
```

After patching the worker to do nothing in `_install_signal_handlers` the worker started, but died as soon as I saved a file:

```
worker_1     | Traceback (most recent call last):
worker_1     |   File "/usr/local/lib/python3.6/site-packages/django/utils/autoreload.py", line 228, in wrapper
worker_1     |     fn(*args, **kwargs)
worker_1     |   File "/backend/django-rq/django_rq/management/commands/rqworker.py", line 132, in inner_handle
worker_1     |     w.work(burst=options.get('burst', False))
worker_1     |   File "/usr/local/lib/python3.6/site-packages/rq/worker.py", line 451, in work
worker_1     |     self.register_birth()
worker_1     |   File "/usr/local/lib/python3.6/site-packages/rq/worker.py", line 260, in register_birth
worker_1     |     raise ValueError(msg.format(self.name))
worker_1     | ValueError: There exists an active worker named '2402' already
```

Then I added a simple `w.register_death()` and everything seems to work perfectly 🎉 

![gif](https://user-images.githubusercontent.com/4096683/33345483-cd77e80a-d48c-11e7-81a5-7a78b3e00b63.gif)

**Comment by honi** [comment]
I implemented a wrapper around the rqworker management command (as another management command) that uses `django.utils.autoreload`. It runs the rqworker using the `subprocess` module, writing the worker's pid to a temp file, which is then read to kill the old rqworker when reloading. Works only on Linux / macOS.

https://gist.github.com/honi/81ba1bff622649a4a2ef7ccf695b1fa0

Feedback welcomed!

**Comment by BenEaston** [comment]
Thank you @honi 
That script works great for me
Much appreciated

**Comment by taewookim** [comment]
If you get 

AttributeError: module 'django.utils.autoreload' has no attribute 'main'


Here's the fix

```
import os
import shlex
import subprocess

from django.core.management.base import BaseCommand
from django.utils import autoreload
from django.utils.autoreload import run_with_reloader


class Command(BaseCommand):
    def add_arguments(self, parser):
        parser.add_argument('--worker-pid-file', action='store', dest='worker_pid_file', default='/tmp/rqworker.pid')

    def handle(self, *args, **options):
        # autoreload.main(run_worker, (options['worker_pid_file'],))
        run_with_reloader(run_worker, options['worker_pid_file'])



def run_worker(worker_pid_file):
    if os.path.exists(worker_pid_file):
        worker_pid = subprocess.run(['cat', worker_pid_file], stdout=subprocess.PIPE).stdout.decode('utf-8')
        kill_worker_cmd = f'kill {worker_pid}'
        subprocess.run(shlex.split(kill_worker_cmd), stderr=subprocess.PIPE)

    start_worker_cmd = f'{get_managepy_path()} rqworker --pid={worker_pid_file}'
    subprocess.run(shlex.split(start_worker_cmd))


def get_managepy_path():
    managepy_path = None
    search_path = os.path.dirname(__file__)
    while not managepy_path:
        if os.path.exists(os.path.join(search_path, 'manage.py')):
            managepy_path = os.path.abspath(os.path.join(search_path, 'manage.py'))
        else:
            search_path = os.path.join(search_path, '../')
    return managepy_path

```

**Comment by taewookim** [comment]
Nvm. I saw your solution [here](https://github.com/rq/rq/issues/2#issuecomment-502364492).
